// <auto-generated />
using System;
using AgroTemp.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgroTemp.Infrastructure.Migrations
{
    [DbContext(typeof(AgroTempDbContext))]
    [Migration("20241014105547_AddExtremeValuesTableToAgroTempDB")]
    partial class AddExtremeValuesTableToAgroTempDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_polish_ci")
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("AgroTemp.Domain.Entities.Alarm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(0)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(0)");

                    b.HasKey("Id");

                    b.ToTable("Alarms", (string)null);
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.DeltaTemperature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(0)");

                    b.Property<int>("ReadingModuleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(0)");

                    b.Property<ushort?>("sensor1")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor10")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor100")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor11")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor12")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor13")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor14")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor15")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor16")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor17")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor18")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor19")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor2")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor20")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor21")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor22")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor23")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor24")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor25")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor26")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor27")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor28")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor29")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor3")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor30")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor31")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor32")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor33")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor34")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor35")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor36")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor37")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor38")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor39")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor4")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor40")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor41")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor42")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor43")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor44")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor45")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor46")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor47")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor48")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor49")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor5")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor50")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor51")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor52")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor53")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor54")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor55")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor56")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor57")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor58")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor59")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor6")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor60")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor61")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor62")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor63")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor64")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor65")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor66")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor67")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor68")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor69")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor7")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor70")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor71")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor72")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor73")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor74")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor75")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor76")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor77")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor78")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor79")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor8")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor80")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor81")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor82")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor83")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor84")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor85")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor86")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor87")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor88")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor89")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor9")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor90")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor91")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor92")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor93")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor94")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor95")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor96")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor97")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor98")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor99")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("ReadingModuleId");

                    b.ToTable("DeltaTemperatures", (string)null);
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.ExtremeValues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(0)");

                    b.Property<int?>("MaxDeltaTemperature")
                        .HasColumnType("int");

                    b.Property<int?>("MaxTemperature")
                        .HasColumnType("int");

                    b.Property<int?>("MinTemperature")
                        .HasColumnType("int");

                    b.Property<int>("SiloId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(0)");

                    b.HasKey("Id");

                    b.HasIndex("SiloId")
                        .IsUnique();

                    b.ToTable("ExtremeValues");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.Probe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<int>("NrFirstSensor")
                        .HasColumnType("int");

                    b.Property<int>("ReadingModuleId")
                        .HasColumnType("int");

                    b.Property<int>("SensorsCount")
                        .HasColumnType("int");

                    b.Property<int>("SiloId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(0)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ReadingModuleId");

                    b.HasIndex("SiloId");

                    b.ToTable("Probes", (string)null);
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.ReadingModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Baudrate")
                        .HasColumnType("int");

                    b.Property<int>("BitsOfSign")
                        .HasColumnType("int");

                    b.Property<string>("CommunicationType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(0)");

                    b.Property<int>("ModuleID")
                        .HasColumnType("int");

                    b.Property<string>("ModuleType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Parity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Port_or_AddressIP")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("StopBit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(0)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ReadingModules", (string)null);
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(0)");

                    b.Property<bool>("EnableEmailNotificationMode")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnableSMSNotificationMode")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("FrequencyOfReading")
                        .HasColumnType("int");

                    b.Property<int>("HourOfReading")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(0)");

                    b.HasKey("Id");

                    b.ToTable("Settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 10, 14, 12, 55, 47, 505, DateTimeKind.Local).AddTicks(4848),
                            EnableEmailNotificationMode = false,
                            EnableSMSNotificationMode = false,
                            FrequencyOfReading = 24,
                            HourOfReading = 12,
                            Language = "ENG",
                            UpdatedAt = new DateTime(2024, 10, 14, 12, 55, 47, 505, DateTimeKind.Local).AddTicks(4911)
                        });
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.Silo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("OrderSensors")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PositionX")
                        .HasColumnType("int");

                    b.Property<int>("PositionY")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(0)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Silos", (string)null);
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.Temperature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(0)");

                    b.Property<int>("ReadingModuleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(0)");

                    b.Property<ushort?>("sensor1")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor10")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor100")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor11")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor12")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor13")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor14")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor15")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor16")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor17")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor18")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor19")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor2")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor20")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor21")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor22")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor23")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor24")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor25")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor26")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor27")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor28")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor29")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor3")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor30")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor31")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor32")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor33")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor34")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor35")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor36")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor37")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor38")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor39")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor4")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor40")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor41")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor42")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor43")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor44")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor45")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor46")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor47")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor48")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor49")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor5")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor50")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor51")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor52")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor53")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor54")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor55")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor56")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor57")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor58")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor59")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor6")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor60")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor61")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor62")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor63")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor64")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor65")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor66")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor67")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor68")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor69")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor7")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor70")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor71")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor72")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor73")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor74")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor75")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor76")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor77")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor78")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor79")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor8")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor80")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor81")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor82")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor83")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor84")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor85")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor86")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor87")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor88")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor89")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor9")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor90")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor91")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor92")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor93")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor94")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor95")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor96")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor97")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor98")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("sensor99")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("ReadingModuleId");

                    b.ToTable("Temperatures", (string)null);
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(0)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TypeOfUser")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(0)");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.DeltaTemperature", b =>
                {
                    b.HasOne("AgroTemp.Domain.Entities.ReadingModule", "ReadingModule")
                        .WithMany("DeltaTemperatures")
                        .HasForeignKey("ReadingModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReadingModule");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.ExtremeValues", b =>
                {
                    b.HasOne("AgroTemp.Domain.Entities.Silo", "Silo")
                        .WithOne("ExtremeValues")
                        .HasForeignKey("AgroTemp.Domain.Entities.ExtremeValues", "SiloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Silo");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.Probe", b =>
                {
                    b.HasOne("AgroTemp.Domain.Entities.ReadingModule", "ReadingModule")
                        .WithMany("Probes")
                        .HasForeignKey("ReadingModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgroTemp.Domain.Entities.Silo", "Silo")
                        .WithMany("Probes")
                        .HasForeignKey("SiloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReadingModule");

                    b.Navigation("Silo");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.Temperature", b =>
                {
                    b.HasOne("AgroTemp.Domain.Entities.ReadingModule", "ReadingModule")
                        .WithMany("Temperatures")
                        .HasForeignKey("ReadingModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReadingModule");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.ReadingModule", b =>
                {
                    b.Navigation("DeltaTemperatures");

                    b.Navigation("Probes");

                    b.Navigation("Temperatures");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.Silo", b =>
                {
                    b.Navigation("ExtremeValues");

                    b.Navigation("Probes");
                });
#pragma warning restore 612, 618
        }
    }
}
