
namespace AgroTemp.Application.Dtos;

public class TemperatureDto
{
	public short? sensor1 { get; set; }
	public short? sensor2 { get; set; }
	public short? sensor3 { get; set; }
	public short? sensor4 { get; set; }
	public short? sensor5 { get; set; }
	public short? sensor6 { get; set; }
	public short? sensor7 { get; set; }
	public short? sensor8 { get; set; }
	public short? sensor9 { get; set; }
	public short? sensor10 { get; set; }
	public short? sensor11 { get; set; }
	public short? sensor12 { get; set; }
	public short? sensor13 { get; set; }
	public short? sensor14 { get; set; }
	public short? sensor15 { get; set; }
	public short? sensor16 { get; set; }
	public short? sensor17 { get; set; }
	public short? sensor18 { get; set; }
	public short? sensor19 { get; set; }
	public short? sensor20 { get; set; }
	public short? sensor21 { get; set; }
	public short? sensor22 { get; set; }
	public short? sensor23 { get; set; }
	public short? sensor24 { get; set; }
	public short? sensor25 { get; set; }
	public short? sensor26 { get; set; }
	public short? sensor27 { get; set; }
	public short? sensor28 { get; set; }
	public short? sensor29 { get; set; }
	public short? sensor30 { get; set; }
	public short? sensor31 { get; set; }
	public short? sensor32 { get; set; }
	public short? sensor33 { get; set; }
	public short? sensor34 { get; set; }
	public short? sensor35 { get; set; }
	public short? sensor36 { get; set; }
	public short? sensor37 { get; set; }
	public short? sensor38 { get; set; }
	public short? sensor39 { get; set; }
	public short? sensor40 { get; set; }
	public short? sensor41 { get; set; }
	public short? sensor42 { get; set; }
	public short? sensor43 { get; set; }
	public short? sensor44 { get; set; }
	public short? sensor45 { get; set; }
	public short? sensor46 { get; set; }
	public short? sensor47 { get; set; }
	public short? sensor48 { get; set; }
	public short? sensor49 { get; set; }
	public short? sensor50 { get; set; }
	public short? sensor51 { get; set; }
	public short? sensor52 { get; set; }
	public short? sensor53 { get; set; }
	public short? sensor54 { get; set; }
	public short? sensor55 { get; set; }
	public short? sensor56 { get; set; }
	public short? sensor57 { get; set; }
	public short? sensor58 { get; set; }
	public short? sensor59 { get; set; }
	public short? sensor60 { get; set; }
	public short? sensor61 { get; set; }
	public short? sensor62 { get; set; }
	public short? sensor63 { get; set; }
	public short? sensor64 { get; set; }
	public short? sensor65 { get; set; }
	public short? sensor66 { get; set; }
	public short? sensor67 { get; set; }
	public short? sensor68 { get; set; }
	public short? sensor69 { get; set; }
	public short? sensor70 { get; set; }
	public short? sensor71 { get; set; }
	public short? sensor72 { get; set; }
	public short? sensor73 { get; set; }
	public short? sensor74 { get; set; }
	public short? sensor75 { get; set; }
	public short? sensor76 { get; set; }
	public short? sensor77 { get; set; }
	public short? sensor78 { get; set; }
	public short? sensor79 { get; set; }
	public short? sensor80 { get; set; }
	public short? sensor81 { get; set; }
	public short? sensor82 { get; set; }
	public short? sensor83 { get; set; }
	public short? sensor84 { get; set; }
	public short? sensor85 { get; set; }
	public short? sensor86 { get; set; }
	public short? sensor87 { get; set; }
	public short? sensor88 { get; set; }
	public short? sensor89 { get; set; }
	public short? sensor90 { get; set; }
	public short? sensor91 { get; set; }
	public short? sensor92 { get; set; }
	public short? sensor93 { get; set; }
	public short? sensor94 { get; set; }
	public short? sensor95 { get; set; }
	public short? sensor96 { get; set; }
	public short? sensor97 { get; set; }
	public short? sensor98 { get; set; }
	public short? sensor99 { get; set; }
	public short? sensor100 { get; set; }
}
