namespace AgroTemp.Domain.Entities;

public class Temperature : Entity
{
	public int ReadingModuleId { get; set; }
	public ReadingModule ReadingModule { get; set; }
	public ushort? sensor1 { get; set; }
	public ushort? sensor2 { get; set; }
	public ushort? sensor3 { get; set; }
	public ushort? sensor4 { get; set; }
	public ushort? sensor5 { get; set; }
	public ushort? sensor6 { get; set; }
	public ushort? sensor7 { get; set; }
	public ushort? sensor8 { get; set; }
	public ushort? sensor9 { get; set; }
	public ushort? sensor10 { get; set; }
	public ushort? sensor11 { get; set; }
	public ushort? sensor12 { get; set; }
	public ushort? sensor13 { get; set; }
	public ushort? sensor14 { get; set; }
	public ushort? sensor15 { get; set; }
	public ushort? sensor16 { get; set; }
	public ushort? sensor17 { get; set; }
	public ushort? sensor18 { get; set; }
	public ushort? sensor19 { get; set; }
	public ushort? sensor20 { get; set; }
	public ushort? sensor21 { get; set; }
	public ushort? sensor22 { get; set; }
	public ushort? sensor23 { get; set; }
	public ushort? sensor24 { get; set; }
	public ushort? sensor25 { get; set; }
	public ushort? sensor26 { get; set; }
	public ushort? sensor27 { get; set; }
	public ushort? sensor28 { get; set; }
	public ushort? sensor29 { get; set; }
	public ushort? sensor30 { get; set; }
	public ushort? sensor31 { get; set; }
	public ushort? sensor32 { get; set; }
	public ushort? sensor33 { get; set; }
	public ushort? sensor34 { get; set; }
	public ushort? sensor35 { get; set; }
	public ushort? sensor36 { get; set; }
	public ushort? sensor37 { get; set; }
	public ushort? sensor38 { get; set; }
	public ushort? sensor39 { get; set; }
	public ushort? sensor40 { get; set; }
	public ushort? sensor41 { get; set; }
	public ushort? sensor42 { get; set; }
	public ushort? sensor43 { get; set; }
	public ushort? sensor44 { get; set; }
	public ushort? sensor45 { get; set; }
	public ushort? sensor46 { get; set; }
	public ushort? sensor47 { get; set; }
	public ushort? sensor48 { get; set; }
	public ushort? sensor49 { get; set; }
	public ushort? sensor50 { get; set; }
	public ushort? sensor51 { get; set; }
	public ushort? sensor52 { get; set; }
	public ushort? sensor53 { get; set; }
	public ushort? sensor54 { get; set; }
	public ushort? sensor55 { get; set; }
	public ushort? sensor56 { get; set; }
	public ushort? sensor57 { get; set; }
	public ushort? sensor58 { get; set; }
	public ushort? sensor59 { get; set; }
	public ushort? sensor60 { get; set; }
	public ushort? sensor61 { get; set; }
	public ushort? sensor62 { get; set; }
	public ushort? sensor63 { get; set; }
	public ushort? sensor64 { get; set; }
	public ushort? sensor65 { get; set; }
	public ushort? sensor66 { get; set; }
	public ushort? sensor67 { get; set; }
	public ushort? sensor68 { get; set; }
	public ushort? sensor69 { get; set; }
	public ushort? sensor70 { get; set; }
	public ushort? sensor71 { get; set; }
	public ushort? sensor72 { get; set; }
	public ushort? sensor73 { get; set; }
	public ushort? sensor74 { get; set; }
	public ushort? sensor75 { get; set; }
	public ushort? sensor76 { get; set; }
	public ushort? sensor77 { get; set; }
	public ushort? sensor78 { get; set; }
	public ushort? sensor79 { get; set; }
	public ushort? sensor80 { get; set; }
	public ushort? sensor81 { get; set; }
	public ushort? sensor82 { get; set; }
	public ushort? sensor83 { get; set; }
	public ushort? sensor84 { get; set; }
	public ushort? sensor85 { get; set; }
	public ushort? sensor86 { get; set; }
	public ushort? sensor87 { get; set; }
	public ushort? sensor88 { get; set; }
	public ushort? sensor89 { get; set; }
	public ushort? sensor90 { get; set; }
	public ushort? sensor91 { get; set; }
	public ushort? sensor92 { get; set; }
	public ushort? sensor93 { get; set; }
	public ushort? sensor94 { get; set; }
	public ushort? sensor95 { get; set; }
	public ushort? sensor96 { get; set; }
	public ushort? sensor97 { get; set; }
	public ushort? sensor98 { get; set; }
	public ushort? sensor99 { get; set; }
	public ushort? sensor100 { get; set; }
}
